<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>ASP.NET_Core_QR_Code_Generator</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="QRCoderNetCore" Version="1.0.0" />
    <PackageReference Include="System.Drawing.Common" Version="4.7.2" />
  </ItemGroup>

</Project>
